# Once code has been merged to master, build the
# static site and deploy it to s3.
name: Deployments

on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: cooncesean/s3-docusaurus-sync-action@cooncesean/tweak-home-dir
        env:
          AWS_DEFAULT_REGION: "us-west-2"
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          PROJECT_NAME: ${{ secrets.PROJECT_NAME }}
  notify:
    runs-on: ubuntu-latest
    steps:
    - uses: voxmedia/github-action-slack-notify-build@v1
      with:
        channel: handboook-updates
        status: SUCCESS
        color: good
        message: 'hello'
      env:
        SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
  # notify:
  #   needs: deploy
  #   steps:
  #     - uses: pullreminders/slack-action@master
  #     env:
  #       SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
  #   with:
  #     args: '{\"channel\":\"C019B86JS7R\",\"text\":\"Hello world\"}'
