# Once code has been merged to master, build the
# static site and deploy it to s3.
name: Deployments

# bare minimal
# TODO: add back in `name: changes`
on: push

jobs:
  changes:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          ref: ${{ github.ref }}
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: npm install js-yaml
      - run: git log
      # - run: git log -1 --name-only --oneline




    # runs-on: ubuntu-latest
    # steps:
    #   - id: file-changes
    #     uses: trilom/file-changes-action@v1.2.3
    #     with:
    #       githubToken: ${{ secrets.GH_API_TOKEN }}  # grants access to the private repo
    #   - name: Optional Fetch Modified Files
    #     if: contains(steps.file-changes.outputs.files_modified, 'yml')
    #     uses: actions/setup-node@v1
    #       with:
    #         node-version: 12
    #     run: |
    #       npm install js-yaml
    #       echo "In Parse Modified Results step."
    #       echo "${{steps.file-changes.outputs.files_modified}}"


    # steps:
    # - uses: actions/checkout@v2
    # - name: Checkout Code
    #   - uses: actions/setup-node@v1
    #     with:
    #       node-version: 12
    #   - run: npm install js-yaml
    #   - run:


# on:
#   push:
#     branches: [master]

# jobs:
#   deploy:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@master
#       - uses: cooncesean/s3-docusaurus-sync-action@cooncesean/tweak-home-dir
#         env:
#           AWS_DEFAULT_REGION: "us-west-2"
#           AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
#           AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
#           AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#           PROJECT_NAME: ${{ secrets.PROJECT_NAME }}
#   notify:
#     needs: deploy
#     runs-on: ubuntu-latest
#     steps:
#     - uses: pullreminders/slack-action@master
#       with:
#         args: '{\"channel\":\"C019B89UYA3\",\"text\":\"New build available at: http://handbook-test.s3-website-us-west-2.amazonaws.com/\"}'
#       env:
#         SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
